# cf. https://github.com/microsoft/onnxruntime/blob/master/tools/ci_build/github/linux/docker/Dockerfile.manylinux2014_cpu
FROM quay.io/pypa/manylinux2014_x86_64:latest

ADD scripts /tmp/scripts

WORKDIR /tmp/scripts
RUN sh /tmp/scripts/install.manylinux.sh

ADD external/vcpkg /opt/vcpkg
ADD ports /opt/ports
WORKDIR /opt/vcpkg
RUN sh /tmp/scripts/install.vcpkg.sh
RUN rm -rf /tmp/scripts
