# cf. https://github.com/microsoft/onnxruntime/blob/master/tools/ci_build/github/linux/docker/Dockerfile.manylinux2014_cpu
FROM lisaong/accera-llvm-manylinux2014:latest

ADD scripts /tmp/scripts

WORKDIR /tmp/scripts
RUN sh /tmp/scripts/install.vulkanloader.sh
RUN rm -rf /tmp/scripts
