FROM quay.io/pypa/manylinux2014_x86_64:latest

ADD scripts /tmp/scripts
WORKDIR /tmp/scripts
RUN sh /tmp/scripts/install.manylinux.sh
RUN sh /tmp/scripts/install.vulkanloader.sh

ADD external/vcpkg /opt/vcpkg
ADD ports /opt/ports
WORKDIR /opt/vcpkg
RUN sh /tmp/scripts/install.vcpkg.sh
RUN rm -rf /tmp/scripts
