# cf. https://vcpkg.readthedocs.io/en/stable/users/binarycaching/
name: Builds the Accera LLVM vcpkg

env:
  VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']
        include:
          - os: 'windows-latest'
            triplet: 'x64-windows'
            mono: ''
            bootstrap: 'bootstrap-vcpkg.bat'
          - os: 'ubuntu-latest'
            triplet: 'x64-linux'
            # To run `nuget.exe` on non-Windows platforms, we must use `mono`.
            mono: 'mono'
            bootstrap: 'bootstrap-vcpkg.sh'
          - os: 'macos-latest'
            triplet: 'x64-osx'
            mono: 'mono'
            bootstrap: 'bootstrap-vcpkg.sh'

    runs-on: ${{ matrix.os }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Bootstrap vcpkg
        run: |
          ./external/vcpkg/${{ matrix.bootstrap }}
