# cf. https://vcpkg.readthedocs.io/en/stable/users/binarycaching/
name: accera-llvm build

env:
  VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'

on:
#  push:
#    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']
        project: ['accera-llvm', 'accera-mlir', 'accera-lld']
        include:
          - os: 'windows-latest'
            triplet: 'x64-windows'
            mono: ''
            bootstrap: 'bootstrap-vcpkg.bat'
          - os: 'ubuntu-latest'
            triplet: 'x64-linux'
            # To run `nuget.exe` on non-Windows platforms, we must use `mono`.
            mono: 'mono'
            bootstrap: 'bootstrap-vcpkg.sh'
          - os: 'macos-latest'
            triplet: 'x64-osx'
            mono: 'mono'
            bootstrap: 'bootstrap-vcpkg.sh'

    runs-on: ${{ matrix.os }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Bootstrap vcpkg
        run: |
          ./external/vcpkg/${{ matrix.bootstrap }}

      - name: Setup NuGet credentials
        shell: 'bash'
        run: >
          ${{ matrix.mono }} `./external/vcpkg/vcpkg fetch nuget | tail -n 1`
          sources add
          -source "https://nuget.pkg.github.com/lisaong/index.json"
          -storepasswordincleartext
          -name "GitHub"
          -username "lisaong"
          -password "${{ secrets.GITHUB_TOKEN }}"
      
      # Currently fails to build because of insufficient disk space
      - name: Install ${{ matrix.project }}
        shell: 'bash'
        run: >
          ./external/vcpkg/vcpkg install ${{ matrix.project }} --triplet ${{ matrix.triplet }} --overlay-ports=ports/${{ matrix.project }}

      - name: Upload build logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: build-logs
          path: external/vcpkg/buildtrees/${{ matrix.project }}/*.log